import { readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";
import {
  normalizeGeneratedSource,
  parseBuildArguments,
  renderSchedulerArtifact,
} from "../scripts/build-tools.js";

describe("generated Scheduler artifact build", () => {
  it("uses the CI-published Draft PR development image", async () => {
    const compose = await readFile(
      new URL("../agent-compose.yml", import.meta.url),
      "utf8",
    );

    expect(compose).toContain(
      "image: ghcr.io/winterfx/agent-compose-guest-dev:main",
    );
    expect(compose).not.toContain("image: agent-compose-guest-dev:local");
  });

  it("passes the configured Git identity to the Draft PR Agent", async () => {
    const compose = await readFile(
      new URL("../agent-compose.yml", import.meta.url),
      "utf8",
    );

    expect(compose).toContain(
      "DRAFT_PR_GIT_AUTHOR_NAME: ${DRAFT_PR_GIT_AUTHOR_NAME}",
    );
    expect(compose).toContain(
      "DRAFT_PR_GIT_AUTHOR_EMAIL: ${DRAFT_PR_GIT_AUTHOR_EMAIL}",
    );
  });

  it("builds every target by default", () => {
    expect(parseBuildArguments([])).toEqual({
      check: false,
      targets: ["issue-triage", "draft-pr"],
    });
    expect(parseBuildArguments(["--check"])).toEqual({
      check: true,
      targets: ["issue-triage", "draft-pr"],
    });
  });

  it("accepts an explicit target and rejects unknown targets", () => {
    expect(parseBuildArguments(["draft-pr"])).toEqual({
      check: false,
      targets: ["draft-pr"],
    });
    expect(() => parseBuildArguments(["unknown"])).toThrow(
      "unknown build target: unknown",
    );
  });

  it("normalizes trailing whitespace deterministically", () => {
    expect(normalizeGeneratedSource("first  \nsecond\t\nthird\n")).toBe(
      "first\nsecond\nthird\n",
    );
  });

  it("embeds one deterministic tool bundle in a scheduler artifact", () => {
    const artifact = renderSchedulerArtifact(
      [
        'const WORKFLOW_TOOL_BASE64 = "__WORKFLOW_TOOL_BASE64__";',
        'const WORKFLOW_POLICY_JSON = "__WORKFLOW_POLICY_JSON__";',
        "",
      ].join("\n"),
      'process.stdout.write("ready");\n',
      '{"enabled":true}\n',
    );

    expect(artifact).toContain("Generated by scripts/build-tools.ts");
    expect(artifact).toContain(
      `const WORKFLOW_TOOL_BASE64 = ${JSON.stringify(Buffer.from('process.stdout.write("ready");\n').toString("base64"))};`,
    );
    expect(artifact).not.toContain("__WORKFLOW_TOOL_BASE64__");
    expect(artifact).toContain(
      'const WORKFLOW_POLICY_JSON = "{\\\"enabled\\\":true}";',
    );
    expect(artifact).not.toContain("__WORKFLOW_POLICY_JSON__");
    expect(() =>
      renderSchedulerArtifact("const value = 1;", "tool", "{}"),
    ).toThrow("exactly one __WORKFLOW_TOOL_BASE64__ placeholder");
  });

  it("keeps the generated bundles free of the Zod locale catalog", async () => {
    const bundles = await Promise.all([
      readFile(
        new URL("../agents/issue-triage/scheduler.js", import.meta.url),
        "utf8",
      ),
      readFile(
        new URL("../agents/draft-pr/scheduler.js", import.meta.url),
        "utf8",
      ),
    ]);

    for (const bundle of bundles) {
      expect(bundle).toContain("Generated by scripts/build-tools.ts");
      expect(bundle).toContain("WORKFLOW_TOOL_BASE64");
      expect(bundle).toContain("WORKFLOW_POLICY_JSON");
      expect(bundle).not.toContain("__WORKFLOW_TOOL_BASE64__");
      expect(bundle).not.toContain("__WORKFLOW_POLICY_JSON__");
      expect(bundle).not.toContain("node_modules/zod/v4/locales/");
    }
  });

  it("pins the Draft PR development image toolchain", async () => {
    const dockerfile = await readFile(
      new URL("../deploy/Dockerfile.agent-compose-guest-dev", import.meta.url),
      "utf8",
    );

    expect(dockerfile).toContain("ARG BUF_VERSION=v1.68.1");
    expect(dockerfile).toContain("ARG TASK_VERSION=v3.45.4");
    expect(dockerfile).toContain("ARG GOLANGCI_LINT_VERSION=v2.5.0");
    expect(dockerfile).toContain(
      "ARG NILAWAY_VERSION=v0.0.0-20260728215154-90f4b4f67ca9",
    );
    expect(dockerfile).toContain(
      "github.com/bufbuild/buf/cmd/buf@${BUF_VERSION}",
    );
    expect(dockerfile).toContain(
      "github.com/go-task/task/v3/cmd/task@${TASK_VERSION}",
    );
    expect(dockerfile).toContain(
      "github.com/golangci/golangci-lint/v2/cmd/golangci-lint@${GOLANGCI_LINT_VERSION}",
    );
    expect(dockerfile).toContain(
      "go.uber.org/nilaway/cmd/nilaway@${NILAWAY_VERSION}",
    );
    expect(dockerfile).toContain(
      "apt-get install -y --no-install-recommends ripgrep",
    );
    expect(dockerfile).not.toContain("docker.io");
    expect(dockerfile).not.toContain("DOCKER_COMPOSE_VERSION");
    expect(dockerfile).not.toContain("jq --version");
    expect(dockerfile).toContain("golangci-lint version");
    expect(dockerfile).toContain("command -v nilaway");
  });
});
