import { readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";
import {
  normalizeGeneratedSource,
  parseBuildArguments,
  renderSchedulerArtifact,
} from "../scripts/build-tools.js";

describe("generated Scheduler artifact build", () => {
  it("builds every target by default", () => {
    expect(parseBuildArguments([])).toEqual({
      check: false,
      targets: ["issue-triage", "draft-pr"],
    });
    expect(parseBuildArguments(["--check"])).toEqual({
      check: true,
      targets: ["issue-triage", "draft-pr"],
    });
  });

  it("accepts an explicit target and rejects unknown targets", () => {
    expect(parseBuildArguments(["draft-pr"])).toEqual({
      check: false,
      targets: ["draft-pr"],
    });
    expect(() => parseBuildArguments(["unknown"])).toThrow(
      "unknown build target: unknown",
    );
  });

  it("normalizes trailing whitespace deterministically", () => {
    expect(normalizeGeneratedSource("first  \nsecond\t\nthird\n")).toBe(
      "first\nsecond\nthird\n",
    );
  });

  it("embeds one deterministic tool bundle in a scheduler artifact", () => {
    const artifact = renderSchedulerArtifact(
      [
        'const WORKFLOW_TOOL_BASE64 = "__WORKFLOW_TOOL_BASE64__";',
        'const WORKFLOW_POLICY_JSON = "__WORKFLOW_POLICY_JSON__";',
        "",
      ].join("\n"),
      'process.stdout.write("ready");\n',
      '{"enabled":true}\n',
    );

    expect(artifact).toContain("Generated by scripts/build-tools.ts");
    expect(artifact).toContain(
      `const WORKFLOW_TOOL_BASE64 = ${JSON.stringify(Buffer.from('process.stdout.write("ready");\n').toString("base64"))};`,
    );
    expect(artifact).not.toContain("__WORKFLOW_TOOL_BASE64__");
    expect(artifact).toContain(
      'const WORKFLOW_POLICY_JSON = "{\\\"enabled\\\":true}";',
    );
    expect(artifact).not.toContain("__WORKFLOW_POLICY_JSON__");
    expect(() =>
      renderSchedulerArtifact("const value = 1;", "tool", "{}"),
    ).toThrow("exactly one __WORKFLOW_TOOL_BASE64__ placeholder");
  });

  it("keeps the generated bundles free of the Zod locale catalog", async () => {
    const bundles = await Promise.all([
      readFile(
        new URL("../agents/issue-triage/scheduler.js", import.meta.url),
        "utf8",
      ),
      readFile(
        new URL("../agents/draft-pr/scheduler.js", import.meta.url),
        "utf8",
      ),
    ]);

    for (const bundle of bundles) {
      expect(bundle).toContain("Generated by scripts/build-tools.ts");
      expect(bundle).toContain("WORKFLOW_TOOL_BASE64");
      expect(bundle).toContain("WORKFLOW_POLICY_JSON");
      expect(bundle).not.toContain("__WORKFLOW_TOOL_BASE64__");
      expect(bundle).not.toContain("__WORKFLOW_POLICY_JSON__");
      expect(bundle).not.toContain("node_modules/zod/v4/locales/");
    }
  });
});
