import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const repositoryRoot = fileURLToPath(new URL("../", import.meta.url));
const workflowPolicyPlaceholder = "__WORKFLOW_POLICY_JSON__";
const workflowToolPathPlaceholder = "__WORKFLOW_TOOL_PATH__";
const generatedFileBanner =
  "// Generated by scripts/build-tools.ts. Do not edit directly.";
// Must match every agents.<name>.workspace.target in agent-compose.yml.
const workspaceToolTarget = "workflow-repo";

const buildTargets = {
  "issue-triage": {
    entryPoint: "src/issue-triage/main.ts",
    schedulerSource: "src/schedulers/issue-triage.js",
    policySource: "agents/issue-triage/policy.json",
    outfile: "agents/issue-triage/scheduler.js",
    toolOutfile: "agents/issue-triage/tool/main.mjs",
  },
  "draft-pr": {
    entryPoint: "src/draft-pr/main.ts",
    schedulerSource: "src/schedulers/draft-pr.js",
    policySource: "agents/draft-pr/policy.json",
    outfile: "agents/draft-pr/scheduler.js",
    toolOutfile: "agents/draft-pr/tool/main.mjs",
  },
} as const;

function toolPath(toolOutfile: string): string {
  return `$WORKSPACE/${workspaceToolTarget}/${toolOutfile}`;
}

export type BuildTargetName = keyof typeof buildTargets;

export interface BuildOptions {
  check: boolean;
  targets: BuildTargetName[];
}

export function normalizeGeneratedSource(source: string): string {
  return source.replace(/[ \t]+$/gm, "");
}

export function renderSchedulerArtifact(
  schedulerSource: string,
  workflowPolicySource: string,
  workflowToolPath: string,
): string {
  let generated = replaceExactlyOnce(
    schedulerSource,
    workflowPolicyPlaceholder,
    JSON.stringify(JSON.parse(workflowPolicySource)),
  );
  generated = replaceExactlyOnce(
    generated,
    workflowToolPathPlaceholder,
    workflowToolPath,
  );
  return withGeneratedFileBanner(generated);
}

export function renderToolArtifact(workflowToolSource: string): string {
  return withGeneratedFileBanner(workflowToolSource);
}

function withGeneratedFileBanner(source: string): string {
  return normalizeGeneratedSource([generatedFileBanner, source].join("\n"));
}

function replaceExactlyOnce(
  source: string,
  placeholderValue: string,
  replacementValue: string,
): string {
  const placeholder = JSON.stringify(placeholderValue);
  const first = source.indexOf(placeholder);
  if (first < 0 || source.indexOf(placeholder, first + 1) >= 0) {
    throw new Error(
      `scheduler source must contain exactly one ${placeholderValue} placeholder`,
    );
  }
  return source.replace(placeholder, () => JSON.stringify(replacementValue));
}

export function parseBuildArguments(args: string[]): BuildOptions {
  const check = args.includes("--check");
  const requested = args.filter((argument) => argument !== "--check");
  const targets = requested.length > 0 ? requested : Object.keys(buildTargets);

  for (const target of targets) {
    if (!(target in buildTargets)) {
      throw new Error(`unknown build target: ${target}`);
    }
  }

  return { check, targets: targets as BuildTargetName[] };
}

async function writeOrCheck(
  relativePath: string,
  generated: string,
  check: boolean,
): Promise<boolean> {
  const outfile = path.join(repositoryRoot, relativePath);

  if (!check) {
    await mkdir(path.dirname(outfile), { recursive: true });
    await writeFile(outfile, generated);
    process.stdout.write(`built ${relativePath}\n`);
    return true;
  }

  const current = await readFile(outfile, "utf8").catch(() => "");
  if (current === generated) {
    process.stdout.write(`checked ${relativePath}\n`);
    return true;
  }
  process.stderr.write(`stale ${relativePath}\n`);
  return false;
}

async function buildTarget(
  targetName: BuildTargetName,
  check: boolean,
): Promise<boolean> {
  const target = buildTargets[targetName];
  const result = await build({
    absWorkingDir: repositoryRoot,
    entryPoints: [target.entryPoint],
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node20",
    outfile: path.join(repositoryRoot, target.outfile),
    write: false,
    logLevel: "silent",
  });
  const output = result.outputFiles?.[0];
  if (!output) throw new Error(`esbuild produced no output for ${targetName}`);
  const [schedulerSource, policySource] = await Promise.all([
    readFile(path.join(repositoryRoot, target.schedulerSource), "utf8"),
    readFile(path.join(repositoryRoot, target.policySource), "utf8"),
  ]);
  const generatedScheduler = renderSchedulerArtifact(
    schedulerSource,
    policySource,
    toolPath(target.toolOutfile),
  );
  const generatedTool = renderToolArtifact(output.text);

  const [schedulerMatched, toolMatched] = await Promise.all([
    writeOrCheck(target.outfile, generatedScheduler, check),
    writeOrCheck(target.toolOutfile, generatedTool, check),
  ]);
  return schedulerMatched && toolMatched;
}

export async function runBuild(options: BuildOptions): Promise<void> {
  const results = await Promise.all(
    options.targets.map((target) => buildTarget(target, options.check)),
  );
  if (results.some((matched) => !matched)) {
    throw new Error(
      "generated Scheduler artifacts are stale; run npm run build",
    );
  }
}

async function main(): Promise<void> {
  await runBuild(parseBuildArguments(process.argv.slice(2)));
}

if (
  process.argv[1] &&
  path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url))
) {
  main().catch((error: unknown) => {
    process.stderr.write(
      `${error instanceof Error ? error.message : String(error)}\n`,
    );
    process.exitCode = 1;
  });
}
